// src/backend/components/utility/AceComponent.vue
<template>
    <textarea id={props.id} readonly
              class="w100p autosize"
              :class="{ 'seamless-input': props.seamless, ... additionalClasses }"
              spellCheck="false"
              translate="no"
              :data-mode="props.mode"
              :data-gutters="props.gutters ? 'true' : null"
              :data-markers="props.markers ? Marker.joinedString(props.markers) : null"
              :data-line-ids="props.lineIds ? stringifyCommonLineIds(props.lineIds) : null"
              :data-in-template="props.inTemplate ? 'true' : null"
              :value="props.value"></textarea>
</template>

<script setup lang="ts">
import { Marker } from '../../../shared/util/highlightMarker';
import { CommonLineId, stringifyCommonLineIds } from '../../../shared/types/common-types';

export type AceProps = {
  id?: string,

  gutters?: boolean,
  seamless?: boolean,
  inTemplate?: boolean,

  markers?: Marker[],
  lineIds?: CommonLineId[],

  mode?: string,
  extraClassNames?: string|string[],
  forOl?: boolean,
  forOlWithCopyButton?: boolean,

  value?: string,
};

const props = defineProps<AceProps>();

let additionalClasses: {[cls: string]: boolean} = {};

if (typeof props.extraClassNames === 'string') {
  for (let cls of props.extraClassNames.split(/\s+/g)) {
    additionalClasses[cls] = true;
  }
}

if (Array.isArray(props.extraClassNames)) {
  for (let str of props.extraClassNames) {
    for (let cls of str.split(/\s+/g)) {
      additionalClasses[cls] = true;
    }
  }
}

if (props.forOl || props.forOlWithCopyButton)
  additionalClasses['ol-result-textarea'] = true;

if (props.forOlWithCopyButton)
  additionalClasses['ol-result-textarea--with-copy-button'] = true;
</script>

// src/backend/components/utility/AceComponent.tsx
import React from 'react';
import classNames from 'classnames';
import { CommonLineId, stringifyCommonLineIds } from '../../../shared/types/common-types';
import { Marker } from '../../../shared/util/highlightMarker';

export type AceProps = {
  id?: string,

  gutters?: boolean,
  seamless?: boolean,
  inTemplate?: boolean,

  markers?: Marker[],
  lineIds?: CommonLineId[],

  mode?: string,
  extraClassNames?: classNames.ArgumentArray,

  value?: string,
};

export default function AceComponent(props: AceProps) {
  return (
    <textarea id={props.id} readOnly
              className={classNames('w100p', 'wikitext', 'autosize', {
                'seamless-input': props.seamless
              }, ... (props.extraClassNames || []))}
              spellCheck="false" translate="no"
              data-mode={props.mode}
              data-gutters={props.gutters ? 'true' : null}
              data-markers={props.markers ? Marker.joinedString(props.markers) : null}
              data-line-ids={props.lineIds ? stringifyCommonLineIds(props.lineIds) : null}
              data-in-template={props.inTemplate ? 'true' : null}
              value={ props.value }
    ></textarea>
  );
}
